CREATE TABLE Tickets(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	AuthorId INT NOT NULL FOREIGN KEY REFERENCES Persons(Id),
	AssigneeId INT NOT NULL FOREIGN KEY REFERENCES Persons(Id),
	TypeId INT NOT NULL FOREIGN KEY REFERENCES Types(Id),
	SubjectId INT NOT NULL FOREIGN KEY REFERENCES Subjects(Id),
	StatusId INT NOT NULL FOREIGN KEY REFERENCES Statuses(Id),
	[Statement] NVARCHAR(MAX),
	[Description] NVARCHAR(MAX),
	EctsMark VARCHAR(1),
	Grade INT,
	Comment NVARCHAR(MAX),
	Deadline DATE
);